// ──────────────────────────────────────────────
// Domain types for the UPSC Quiz system
// ──────────────────────────────────────────────

/** A single MCQ as generated by the AI. */
export interface GeneratedQuestion {
  question: string;
  options: [string, string, string, string];
  correctAnswer: string;
  explanation: string;
  confidence: number;
}

/** Result of the anti-hallucination validation pass. */
export interface ValidationResult {
  isValid: boolean;
  correctedAnswer: string;
  issues: string;
}

/** A validated, consumer-ready question (without the answer). */
export interface QuizQuestion {
  id: string;
  question: string;
  options: [string, string, string, string];
}

/** Internal question record stored in memory (includes answer & meta). */
export interface StoredQuestion {
  id: string;
  question: string;
  options: [string, string, string, string];
  correctAnswer: string;
  explanation: string;
}

/** Full quiz stored in the in-memory map. */
export interface StoredQuiz {
  quizId: string;
  topic: string;
  questions: StoredQuestion[];
  createdAt: Date;
}

/** Single answer submitted by the user. */
export interface SubmittedAnswer {
  questionId: string;
  selected: string;
}

/** AI-generated performance analysis. */
export interface QuizAnalysis {
  strengths: string[];
  weaknesses: string[];
  summary: string;
  suggestions: string[];
}

/** Response payload for POST /generate-quiz. */
export interface GenerateQuizResponse {
  quizId: string;
  questions: QuizQuestion[];
}

/** Response payload for POST /submit-quiz. */
export interface SubmitQuizResponse {
  score: number;
  total: number;
  analysis: QuizAnalysis;
}
